### ISSUE TITLE
Clean up Tilemap

### ISSUE THREAD

**Issue by lishaduck** [PHS-TSA/wizards-in-calculus#25]
### Why

There're a lot of unused tiles.

### The Plan

```[tasklist]
#### Tasks
- [ ] Remove tiles w/background.
- [ ] Add more tiles (Maybe a below-slope tile?)
- [ ] https://github.com/PHS-TSA/wizards-in-calculus/issues/34
```

**Comment by lishaduck** [comment]
Additionally, we should add a terrain set, which will automatically add the nice edges when placing tiles.
