### ISSUE TITLE
Update Software

### ISSUE THREAD

**Issue by lishaduck** [PHS-TSA/wizards-in-calculus#32]
### Why

We're using large files (images), so we shouldn't track them directly in Git.

### The Plan

```[tasklist]
#### Tasks
- [ ] Make sure everyone has `git-lfs`
- [ ] Migrate images to use LFS
- [ ] Upgrade Godot to 4.2 for everyone
```
