### ISSUE TITLE
Write GUTs

### ISSUE THREAD

**Issue by lishaduck** [PHS-TSA/wizards-in-calculus#39]
### Why

[It](https://gut.readthedocs.io/en/latest/index.html)'ll make sure we don't break things.
And it sounds funny 🤣.

### The Plan

```[tasklist]
#### Tasks
- [ ] Learn how to write GUTs.
- [ ] Write some GUTs.
- [ ] Run GUTs in CI.
```
