### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by lishaduck** [PHS-TSA/wizards-in-calculus#5]
### Why

We need to get an automated web build so it can be submitted when time comes and, in the meantime, so that we can show it to people w/out Godot.

### The Plan

```[tasklist]
#### Tasks
- [x] Build it
- [x] Set up CD
- [x] Maybe set up CI too? We can use [`Scony/godot-gdscript-toolkit`](https://github.com/Scony/godot-gdscript-toolkit)
- [ ] If we set up CI, we should also setup [automated testing](https://gut.readthedocs.io/en/latest/)
```

**Comment by lishaduck** [comment]
Currently blocked on #24.

**Comment by lishaduck** [comment]
@MattsAttack, do we want deploy previews? I'd say yes, but it's a (teeny-tiny) bit of a hassle.

**Comment by lishaduck** [comment]
> @MattsAttack, do we want deploy previews? I'd say yes, but it's a (teeny-tiny) bit of a hassle.

Went ahead with it, becuase it also gave us more control over compression and mime-types.
